import unittest
from rail_fence_cipher import fence_cipher_encrypt, fence_cipher_encrypt_by_blocks, fence_cipher_decrypt, fence_cipher_decrypt_by_blocks

class TestProgram(unittest.TestCase):
    def test_encrypt(self):
        self.assertEqual(fence_cipher_encrypt('CRYPTOGRAPHY', 3), 'YGHRPORPYCTA')
        self.assertEqual(fence_cipher_encrypt('КРИПТОГРАФІЯ', 3), 'ИГІРПОРФЯКТА')
        self.assertEqual(fence_cipher_encrypt('CRYPTOGRAPHY', 2), 'RPORPYCYTGAH')
        self.assertEqual(fence_cipher_encrypt('CRYPTOGRAPHY', 1), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_encrypt("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", 3), "rIm pdyxfeinnyennt ep  nedr ndmt rnt1shanwreoal t  aet et cnoIauvno eni  oeanetiyenrigsiycg wplsih9 hele rte tiLmspa,dretw k lisw edPMrcivi Lmsoe pu ssml um eto h rnigadtpstigidsr.LrmIsmhsbe h nutyssadr um etee ic h 50,we nukonpitrto  alyo yeadsrmldi omk  yeseie ok thssrie o nyfv etre,btas h epit lcrnctpstig eann setal nhne.I a ouaie nte16swt h ees fLtae hescnann oe pu asgs n oercnl ihdstppbihn otaelk lu aeae nldn esoso oe puLmsiiymt tpt  et uyo uaetis'tadyxvsee0 n n n kgefpncb taappmb.  vdtlicusultl oeo et,mienluadtsprd  0itraoesstoigrImseam eyteousgfriAsgkiugrnfrIm")

    def test_decrypt(self):
        self.assertEqual(fence_cipher_decrypt('YGHRPORPYCTA', 3), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_decrypt('ИГІРПОРФЯКТА', 3), 'КРИПТОГРАФІЯ')
        self.assertEqual(fence_cipher_decrypt('RPORPYCYTGAH', 2), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_decrypt('CRYPTOGRAPHY', 1), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_decrypt("rIm pdyxfeinnyennt ep  nedr ndmt rnt1shanwreoal t  aet et cnoIauvno eni  oeanetiyenrigsiycg wplsih9 hele rte tiLmspa,dretw k lisw edPMrcivi Lmsoe pu ssml um eto h rnigadtpstigidsr.LrmIsmhsbe h nutyssadr um etee ic h 50,we nukonpitrto  alyo yeadsrmldi omk  yeseie ok thssrie o nyfv etre,btas h epit lcrnctpstig eann setal nhne.I a ouaie nte16swt h ees fLtae hescnann oe pu asgs n oercnl ihdstppbihn otaelk lu aeae nldn esoso oe puLmsiiymt tpt  et uyo uaetis'tadyxvsee0 n n n kgefpncb taappmb.  vdtlicusultl oeo et,mienluadtsprd  0itraoesstoigrImseam eyteousgfriAsgkiugrnfrIm", 3), "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum")

    def test_encrypted_by_blocks(self):
        self.assertEqual(fence_cipher_encrypt_by_blocks('CRYPTOGRAPHY', 3, 4), 'YRPCGORTHPYA')
        self.assertEqual(fence_cipher_encrypt_by_blocks('CRYPTOGRAPHY', 2, 6), 'RPOCYTRPYGAH')
        self.assertEqual(fence_cipher_encrypt_by_blocks("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum", 4, 10), "eurmso pLIsli p smmiuedmt m yyo  fet hxtnait rigpntt yedpsnegsn uiidtn.my erLrtosspuaImh  e eneb h tusds'ntyira tndsdr amtmyxu edtecvrne i sh0te0  5e1wn ha,e snkpnn uon wtoneoirtr  yage alkl aft oye psl cbdrmnaim t d oet eeapk yate pcnsie mkho. o tbIse uvsriavoyntl  ndovtienf e cetisur,bu s loea h tp a oeitlnccetilrneopiyettst e n,rigeanm tgennseislhlyca niue gdtn.Ia  asplaouwpetsd i nri1w 9 e6sh0 ehtrth iesLae e floahrsste etsat tecneoneigrn oiLpaIsp u mmgnaeass s,ocmre erd lhtytn iewspek dtp oi lsgbhnuitlfw oaesr  eAskluide gMraaePkl cugndniisori eosvnopLrI e fmsum")

    def test_decrypted_by_blocks(self):
        self.assertEqual(fence_cipher_decrypt_by_blocks('YRPCGORTHPYA', 3, 4), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_decrypt_by_blocks('RPOCYTRPYGAH', 2, 6), 'CRYPTOGRAPHY')
        self.assertEqual(fence_cipher_decrypt_by_blocks("eurmso pLIsli p smmiuedmt m yyo  fet hxtnait rigpntt yedpsnegsn uiidtn.my erLrtosspuaImh  e eneb h tusds'ntyira tndsdr amtmyxu edtecvrne i sh0te0  5e1wn ha,e snkpnn uon wtoneoirtr  yage alkl aft oye psl cbdrmnaim t d oet eeapk yate pcnsie mkho. o tbIse uvsriavoyntl  ndovtienf e cetisur,bu s loea h tp a oeitlnccetilrneopiyettst e n,rigeanm tgennseislhlyca niue gdtn.Ia  asplaouwpetsd i nri1w 9 e6sh0 ehtrth iesLae e floahrsste etsat tecneoneigrn oiLpaIsp u mmgnaeass s,ocmre erd lhtytn iewspek dtp oi lsgbhnuitlfw oaesr  eAskluide gMraaePkl cugndniisori eosvnopLrI e fmsum", 4, 10), "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum")

if __name__ == "__main__":
    unittest.main(exit=False)